// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebRTCConference.Data;

namespace webrtc_conference.Migrations
{
    [DbContext(typeof(ConferenceContext))]
    partial class ConferenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview8.19405.11");

            modelBuilder.Entity("WebRTCConference.Data.Conference", b =>
                {
                    b.Property<int>("ConferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConferenceId");

                    b.ToTable("Conferences");

                    b.HasData(
                        new
                        {
                            ConferenceId = 1,
                            Name = "Testing Conference",
                            ParticipantCount = 5
                        },
                        new
                        {
                            ConferenceId = 2,
                            Name = "Meeting 2",
                            ParticipantCount = 14
                        },
                        new
                        {
                            ConferenceId = 3,
                            Name = "Morbi leo risus",
                            ParticipantCount = 1
                        });
                });

            modelBuilder.Entity("WebRTCConference.Data.Participant", b =>
                {
                    b.Property<string>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantId");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("WebRTCConference.Data.Participant", b =>
                {
                    b.HasOne("WebRTCConference.Data.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
